# 01_docker_node_app/Dockerfile
FROM node:20-alpine

WORKDIR /usr/src/app

COPY package.json package-lock.json* ./
RUN npm install --production || npm install --production --legacy-peer-deps

COPY . .

EXPOSE 3000

CMD ["npm", "start"]
